# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a1a33f5b590f87e312edececb20d46083e7864e7889d9a01ebf45c4b2d3215924abb06a8ed4044879cd68911f2512600066ba8e4f08a647302691e859dfa21b3

test:
  secret_key_base: a4339a8f898d5a17deb8dd1477ee002b2eac05b481c1132634e4e38391ad4aed73fb131a72070a2ede5ffc85716b64e8676e83712a0d5e369994ca87637c02d1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
